remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta Activation]
description: [Jakarta Activation Specification and Implementation]

links:
  source: https://github.com/eclipse-ee4j/jaf
  javadocs: docs/api/
  download: https://github.com/eclipse-ee4j/jaf/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jaf-dev
  #faq: FAQ

include:
  - LICENSE.md
  - CONTRIBUTING.md
